### ISSUE TITLE
The hooks just don't work

### ISSUE THREAD

**Issue by ilearnio** [ssnepenthe/clockwork-for-wp#26]
The hooks `cfw_config_args` and `cfw_config_init` are never triggered. I was trying to listen to them from my theme's function PHP

```php
add_action('cfw_config_init', function () {
  var_dump('yoyoy');
  die;
});
add_filter('cfw_config_args', function ($config) {
  var_dump('yoyoy');
  return $config;
});
```

Also `clock` function doesn't work. Should I use some namespace for it?

**Comment by ssnepenthe** [comment]
The `cfw_config_args` filter was removed - looks like I forgot to update the docs. I will take care of that shortly.

The `cfw_config_init` action is triggered before themes are loaded. You have to use this hook from a plugin or must-use plugin. I will also add this note to the docs shortly.

I typically create a mu-plugin at e.g. wp-content/mu-plugins/cfw-config.php with content like this:

```php
add_action( 'cfw_config_init', function( $config ) {
    $config->set( 'data_sources.wp_hook.enabled', true );

    // etc.
} );
```

The global `clock` function isn't currently registered. It's on my list of things to do, just never got around to it.

The adapted function from [here](https://github.com/itsgoingd/clockwork/blob/master/Clockwork/Support/Laravel/helpers.php) would look like this (untested) if you want to add it yourself:

```php
if ( ! function_exists( 'clock' ) ) {
	// Log a message to Clockwork, returns Clockwork instance when called with no arguments, first argument otherwise
	function clock( ...$arguments ) {
		if ( empty( $arguments ) ) {
			return _cfw_instance()[ \Clockwork\Clockwork::class ];
		}

		foreach ( $arguments as $argument ) {
			_cfw_instance()[ \Clockwork\Clockwork::class ]->debug( $argument );
		}

		return reset( $arguments );
	}
}
```
